def get() -> str:
    return (
        'You are extracting episode data from a TV series page.\n'
        'Extract ALL episodes you can find on the page. Look for tables, lists, '
        'or any structured data.\n\n'
        'For each episode extract:\n'
        '- episode_in_season: The episode number within its season (1, 2, 3... '
        'resets each season)\n'
        '- overall_episode_number: The absolute episode number across all seasons '
        '(continues counting)\n'
        '- title: string (clean title without markdown formatting)\n'
        '- premiere_date: string (date format as found on page; if multiple dates '
        'separated by "/" like "31.12.2008", extract ONLY the FIRST date: '
        '"31.12.2008")\n'
        '- viewership: string (remove spaces from numbers like "4 396 564" -> '
        '"4396564", use null if not available)\n\n'
        'The season number should be determined from the page content or URL.\n\n'
        'Return ONLY valid JSON matching this schema:\n'
        '{\n'
        '  "season_number": int,\n'
        '  "episodes": [\n'
        '    {\n'
        '      "episode_in_season": int,\n'
        '      "overall_episode_number": int,\n'
        '      "title": str,\n'
        '      "premiere_date": str,\n'
        '      "viewership": str\n'
        '    }\n'
        '  ]\n'
        '}'
    )
