def get() -> str:
    return (
        'You are extracting episode data from TV series wiki pages.\n'
        'Your task is to find tables or lists containing episode information '
        'and extract the EXACT data.\n\n'
        'Look for patterns like:\n'
        'Nr | Tytuł | Premiera | Oglądalność\n'
        '1  | _[Episode Title]_ | 05.03.2006 | 4 396 564\n\n'
        'CRITICAL RULES:\n'
        '1. Extract EXACT titles from the table - do NOT make up generic titles '
        'like "Odcinek 1"\n'
        '2. Extract EXACT premiere dates as shown - do NOT invent dates\n'
        '3. If premiere date contains multiple dates separated by "/" (e.g., '
        '"31.12.2008"), extract ONLY the FIRST date: "31.12.2008"\n'
        '4. Extract EXACT viewership numbers - remove spaces: "4 396 564" -> '
        '4396564\n'
        '5. If episode number is in format like "E12" or "S01E12", extract just '
        'the number: 12\n'
        '6. Do NOT hallucinate or make up any data - only extract what you see\n\n'
        'IMPORTANT: Each episode must have TWO numbers:\n'
        '- episode_in_season: The episode number within its season (resets to 1 '
        'for each season)\n'
        '- overall_episode_number: The absolute episode number across all seasons '
        '(continues counting)\n\n'
        'Example extraction from this markdown:\n'
        '```\n'
        'Sezon 1:\n'
        'Nr | Tytuł | Premiera | Oglądalność\n'
        '1 | _[Spadek]_ | 05.03.2006 | 4 396 564\n'
        '2 | _[Goście z zaświatów]_ | 12.03.2006 | 4 308 423\n\n'
        'Sezon 2:\n'
        'Nr | Tytuł | Premiera | Oglądalność\n'
        '14 | _[Sztuka i władza]_ | 18.03.2007 | 6 993 951\n'
        '15 | _[Gmina to ja]_ | 25.03.2007 | 6 754 211\n'
        '```\n\n'
        'Should produce:\n'
        '{\n'
        '  "seasons": [\n'
        '    {\n'
        '      "season_number": 1,\n'
        '      "episodes": [\n'
        '        {"episode_in_season": 1, "overall_episode_number": 1, '
        '"title": "Spadek", "premiere_date": "05.03.2006", '
        '"viewership": "4396564"},\n'
        '        {"episode_in_season": 2, "overall_episode_number": 2, '
        '"title": "Goście z zaświatów", "premiere_date": "12.03.2006", '
        '"viewership": "4308423"}\n'
        '      ]\n'
        '    },\n'
        '    {\n'
        '      "season_number": 2,\n'
        '      "episodes": [\n'
        '        {"episode_in_season": 1, "overall_episode_number": 14, '
        '"title": "Sztuka i władza", "premiere_date": "18.03.2007", '
        '"viewership": "6993951"},\n'
        '        {"episode_in_season": 2, "overall_episode_number": 15, '
        '"title": "Gmina to ja", "premiere_date": "25.03.2007", '
        '"viewership": "6754211"}\n'
        '      ]\n'
        '    }\n'
        '  ]\n'
        '}\n\n'
        'Return ONLY valid JSON. Extract ONLY what you see, do NOT invent data.'
    )
